// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YallaFit.Data;

#nullable disable

namespace YallaFit.Migrations
{
    [DbContext(typeof(YallaFitDbContext))]
    [Migration("20251214215454_FixMissingExerciseColumns")]
    partial class FixMissingExerciseColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("YallaFit.Models.Aliment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Calories100g")
                        .HasColumnType("int")
                        .HasColumnName("calories_100g");

                    b.Property<float>("Glucides100g")
                        .HasPrecision(5, 2)
                        .HasColumnType("float")
                        .HasColumnName("glucides_100g");

                    b.Property<float>("Lipides100g")
                        .HasPrecision(5, 2)
                        .HasColumnType("float")
                        .HasColumnName("lipides_100g");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nom");

                    b.Property<float>("Proteines100g")
                        .HasPrecision(5, 2)
                        .HasColumnType("float")
                        .HasColumnName("proteines_100g");

                    b.HasKey("Id");

                    b.ToTable("Aliment");
                });

            modelBuilder.Entity("YallaFit.Models.BiometrieActuelle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateMesure")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_mesure");

                    b.Property<float>("PoidsKg")
                        .HasPrecision(5, 2)
                        .HasColumnType("float")
                        .HasColumnName("poids_kg");

                    b.Property<int>("SportifId")
                        .HasColumnType("int")
                        .HasColumnName("sportif_id");

                    b.Property<float?>("TauxMasseGrassePercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("float")
                        .HasColumnName("taux_masse_grasse_percent");

                    b.Property<float?>("TourDeTailleCm")
                        .HasPrecision(5, 2)
                        .HasColumnType("float")
                        .HasColumnName("tour_de_taille_cm");

                    b.HasKey("Id");

                    b.HasIndex("SportifId", "DateMesure");

                    b.ToTable("Biometrie_Actuelle");
                });

            modelBuilder.Entity("YallaFit.Models.CompositionRepas", b =>
                {
                    b.Property<int>("RepasId")
                        .HasColumnType("int")
                        .HasColumnName("repas_id");

                    b.Property<int>("AlimentId")
                        .HasColumnType("int")
                        .HasColumnName("aliment_id");

                    b.Property<int>("QuantiteGrammes")
                        .HasColumnType("int")
                        .HasColumnName("quantite_grammes");

                    b.HasKey("RepasId", "AlimentId");

                    b.HasIndex("AlimentId");

                    b.ToTable("Composition_Repas");
                });

            modelBuilder.Entity("YallaFit.Models.DetailSeance", b =>
                {
                    b.Property<int>("SeanceId")
                        .HasColumnType("int")
                        .HasColumnName("seance_id");

                    b.Property<int>("ExerciceId")
                        .HasColumnType("int")
                        .HasColumnName("exercice_id");

                    b.Property<float?>("PoidsConseille")
                        .HasPrecision(6, 2)
                        .HasColumnType("float")
                        .HasColumnName("poids_conseille");

                    b.Property<int>("Repetitions")
                        .HasColumnType("int")
                        .HasColumnName("repetitions");

                    b.Property<int>("Series")
                        .HasColumnType("int")
                        .HasColumnName("series");

                    b.HasKey("SeanceId", "ExerciceId");

                    b.HasIndex("ExerciceId");

                    b.ToTable("Detail_Seance");
                });

            modelBuilder.Entity("YallaFit.Models.Exercice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categorie")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("categorie");

                    b.Property<string>("MuscleCible")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("muscle_cible");

                    b.Property<string>("MusclesCibles")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("muscles_cibles");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nom");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("video_url");

                    b.HasKey("Id");

                    b.ToTable("Exercice");
                });

            modelBuilder.Entity("YallaFit.Models.PlanNutrition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateGeneration")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_generation");

                    b.Property<bool>("EstActif")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("est_actif");

                    b.Property<int>("ObjectifCaloriqueJournalier")
                        .HasColumnType("int")
                        .HasColumnName("objectif_calorique_journalier");

                    b.Property<int>("ObjectifGlucidesG")
                        .HasColumnType("int")
                        .HasColumnName("objectif_glucides_g");

                    b.Property<int>("ObjectifLipidesG")
                        .HasColumnType("int")
                        .HasColumnName("objectif_lipides_g");

                    b.Property<int>("ObjectifProteinesG")
                        .HasColumnType("int")
                        .HasColumnName("objectif_proteines_g");

                    b.Property<int>("SportifId")
                        .HasColumnType("int")
                        .HasColumnName("sportif_id");

                    b.HasKey("Id");

                    b.HasIndex("SportifId");

                    b.ToTable("Plan_Nutrition");
                });

            modelBuilder.Entity("YallaFit.Models.ProfilSportif", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int?>("Age")
                        .HasColumnType("int")
                        .HasColumnName("age");

                    b.Property<string>("Allergies")
                        .HasColumnType("longtext")
                        .HasColumnName("allergies");

                    b.Property<DateTime?>("DateNaissance")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_naissance");

                    b.Property<string>("Genre")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("genre");

                    b.Property<string>("NiveauActivite")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("niveau_activite");

                    b.Property<string>("ObjectifPrincipal")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("objectif_principal");

                    b.Property<decimal?>("Poids")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("poids");

                    b.Property<string>("PreferencesAlim")
                        .HasColumnType("longtext")
                        .HasColumnName("preferences_alim");

                    b.Property<string>("ProblemesSante")
                        .HasColumnType("longtext")
                        .HasColumnName("problemes_sante");

                    b.Property<int?>("ProgrammeId")
                        .HasColumnType("int")
                        .HasColumnName("programme_id");

                    b.Property<string>("Sexe")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("sexe");

                    b.Property<decimal?>("Taille")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("taille");

                    b.Property<int?>("TailleCm")
                        .HasColumnType("int")
                        .HasColumnName("taille_cm");

                    b.HasKey("UserId");

                    b.HasIndex("ProgrammeId");

                    b.ToTable("Profil_Sportif");
                });

            modelBuilder.Entity("YallaFit.Models.Programme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CoachId")
                        .HasColumnType("int")
                        .HasColumnName("coach_id");

                    b.Property<int>("DureeSemaines")
                        .HasColumnType("int")
                        .HasColumnName("duree_semaines");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_public");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("titre");

                    b.HasKey("Id");

                    b.HasIndex("CoachId");

                    b.ToTable("Programme");
                });

            modelBuilder.Entity("YallaFit.Models.Repas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("HeurePrevue")
                        .HasColumnType("time(6)")
                        .HasColumnName("heure_prevue");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nom");

                    b.Property<int>("PlanId")
                        .HasColumnType("int")
                        .HasColumnName("plan_id");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.ToTable("Repas");
                });

            modelBuilder.Entity("YallaFit.Models.Seance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("JourSemaine")
                        .HasColumnType("int")
                        .HasColumnName("jour_semaine");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nom");

                    b.Property<int>("ProgrammeId")
                        .HasColumnType("int")
                        .HasColumnName("programme_id");

                    b.HasKey("Id");

                    b.HasIndex("ProgrammeId");

                    b.ToTable("Seance");
                });

            modelBuilder.Entity("YallaFit.Models.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("email");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("mot_de_passe");

                    b.Property<string>("NomComplet")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nom_complet");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Utilisateur");
                });

            modelBuilder.Entity("YallaFit.Models.BiometrieActuelle", b =>
                {
                    b.HasOne("YallaFit.Models.Utilisateur", "Sportif")
                        .WithMany("BiometriesMeasurements")
                        .HasForeignKey("SportifId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sportif");
                });

            modelBuilder.Entity("YallaFit.Models.CompositionRepas", b =>
                {
                    b.HasOne("YallaFit.Models.Aliment", "Aliment")
                        .WithMany("CompositionRepas")
                        .HasForeignKey("AlimentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("YallaFit.Models.Repas", "Repas")
                        .WithMany("CompositionRepas")
                        .HasForeignKey("RepasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aliment");

                    b.Navigation("Repas");
                });

            modelBuilder.Entity("YallaFit.Models.DetailSeance", b =>
                {
                    b.HasOne("YallaFit.Models.Exercice", "Exercice")
                        .WithMany("DetailSeances")
                        .HasForeignKey("ExerciceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("YallaFit.Models.Seance", "Seance")
                        .WithMany("DetailSeances")
                        .HasForeignKey("SeanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercice");

                    b.Navigation("Seance");
                });

            modelBuilder.Entity("YallaFit.Models.PlanNutrition", b =>
                {
                    b.HasOne("YallaFit.Models.Utilisateur", "Sportif")
                        .WithMany("PlansNutrition")
                        .HasForeignKey("SportifId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sportif");
                });

            modelBuilder.Entity("YallaFit.Models.ProfilSportif", b =>
                {
                    b.HasOne("YallaFit.Models.Programme", "Programme")
                        .WithMany()
                        .HasForeignKey("ProgrammeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("YallaFit.Models.Utilisateur", "Utilisateur")
                        .WithOne("ProfilSportif")
                        .HasForeignKey("YallaFit.Models.ProfilSportif", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Programme");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("YallaFit.Models.Programme", b =>
                {
                    b.HasOne("YallaFit.Models.Utilisateur", "Coach")
                        .WithMany("ProgrammesCreated")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("YallaFit.Models.Repas", b =>
                {
                    b.HasOne("YallaFit.Models.PlanNutrition", "Plan")
                        .WithMany("Repas")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("YallaFit.Models.Seance", b =>
                {
                    b.HasOne("YallaFit.Models.Programme", "Programme")
                        .WithMany("Seances")
                        .HasForeignKey("ProgrammeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Programme");
                });

            modelBuilder.Entity("YallaFit.Models.Aliment", b =>
                {
                    b.Navigation("CompositionRepas");
                });

            modelBuilder.Entity("YallaFit.Models.Exercice", b =>
                {
                    b.Navigation("DetailSeances");
                });

            modelBuilder.Entity("YallaFit.Models.PlanNutrition", b =>
                {
                    b.Navigation("Repas");
                });

            modelBuilder.Entity("YallaFit.Models.Programme", b =>
                {
                    b.Navigation("Seances");
                });

            modelBuilder.Entity("YallaFit.Models.Repas", b =>
                {
                    b.Navigation("CompositionRepas");
                });

            modelBuilder.Entity("YallaFit.Models.Seance", b =>
                {
                    b.Navigation("DetailSeances");
                });

            modelBuilder.Entity("YallaFit.Models.Utilisateur", b =>
                {
                    b.Navigation("BiometriesMeasurements");

                    b.Navigation("PlansNutrition");

                    b.Navigation("ProfilSportif");

                    b.Navigation("ProgrammesCreated");
                });
#pragma warning restore 612, 618
        }
    }
}
